### ISSUE TITLE
Automate job-board enforcement

### ISSUE THREAD

**Issue by vcarl** [reactiflux/reactibot#141]
I've been manually enforcing our rules, which has been a good bit of time investment. The biggest rule we have is posting once a week.

A naive implementation could scan posts to `#job-board` and remove/warn members who post too frequently, but that's pretty trivial to circumvent by deleting your own posts.

To fix that loophole, Reactibot could log when a member deletes their post with a date stamp of when it was originally posted.

**Comment by taranvohra** [comment]
Where would we log that info? Are we going to have a DB for reactibot?

**Comment by vcarl** [comment]
I was thinking it'd be okay to do stateless scans of the past N messages. Some thoughts I put together:

on startup, load #job-board messages into memory until we find once that's > 1 week old
every 4 hours, scan for posts that violate job board rules
* load posts more recent than the last
* unload any that are now > 1 week old
* iterate through final list, build index of message content and authors and warn/remove duplicates

**Comment by vcarl** [comment]
Eventually, I think it'd be good to have an SQLite db or something so we can add persistence for features, but I keep finding ways to accomplish goals without it

**Comment by taranvohra** [comment]
Yeah that seems fair. Is there any particular reason for doing it every 4 hours instead of doing it on demand? I feel we can just keep building and updating the 1 week index list on every message sent in #job-board and find violations that moment.

So like after startup we have an initial 1 week messages then on every message we get in #job-board, if it's not a violation, we add it to our index, unload the existing > 1 week old messages.

**Comment by vcarl** [comment]
Excellent point, that would in fact be much simpler

**Comment by taranvohra** [comment]
Great. I'd like to work on this.

**Comment by vcarl** [comment]
@taranvohra I've got a WIP branch! I'll push up a draft PR, I've got the fetch working at least.
