### ISSUE TITLE
!close

### ISSUE THREAD

**Issue by Padmanabh82** [reactiflux/reactibot#176]
I think we need a close command for threads, use case - if we solved problem by our own, if no one is answering or it hase been answering, etc

**Comment by nickmccurdy** [comment]
Would archiving the thread work instead?

**Comment by Padmanabh82** [comment]
> Would archiving the thread work instead?

@nickmccurdy it's same

**Comment by Padmanabh82** [comment]
Should we change command !close to ! archive ??

**Comment by nickmccurdy** [comment]
We don't need a command to archive, it's part of Discord

**Comment by Padmanabh82** [comment]
> We don't need a command to archive, it's part of Discord

But then we need to wait for 12 hours

**Comment by vcarl** [comment]
I'm not sure what problem this solves, an old thread hanging around doesn't really have a cost. If it bothers you to see it in the sidebar, you can leave it, and it'll time out same as any other thread 
![image](https://user-images.githubusercontent.com/1551487/151878208-4529429c-d058-4000-8aec-9518a0f3c09d.png)

I'm going to close this out because I don't think it's a change we'll make in the immediate term
